version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: nlinfoDB-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongrootpassword
      MYSQL_DATABASE: nlinfoDB
    ports:
    - "3307:3306"
    cap_add:
      - SYS_NICE


  app:
     image: vandersonmauricio/nlinfochallenge:V1
     container_name: nlinfo_app
     depends_on:
       - mysql-db
     environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/nlinfoDB
       HABILITAR_CARREGAR_MASSA_DADOS: 'false'
     ports:
       - "9090:8080" #host:container